---
- name: Deploy IPFS, and Hippius nodes
  hosts: ipfs_nodes
  become: yes

  roles:
    - { role: common, tags: ['common'] }
    - { role: ipfs, tags: ['ipfs'] }
    - { role: index-provider, tags: ['index-provider'] }
    - { role: hippius, tags: ['hippius'] }
    - { role: miner-ipfs-service, tags: ['miner-ipfs-service'] }

  post_tasks:
    - name: Display node IDs
      include_tasks: roles/common/tasks/display_node_ids.yml
      tags: ['always']
