---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
    update_cache: yes
  become: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  become: yes

- name: Install docker-compose-plugin
  apt:
    name: docker-compose-plugin
    state: present
  become: yes

- name: Reset Docker service
  systemd:
    name: docker
    state: stopped
    daemon_reload: yes
  become: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Wait for Docker to be ready
  wait_for:
    timeout: 30

- name: Create directory for subtensor
  file:
    path: "/opt/subtensor"
    state: directory
    mode: '0755'

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/subtensor/docker-compose.yml
    mode: '0644'

- name: Pull subtensor image
  docker_image:
    name: "{{ subtensor_image }}"
    source: pull
    force_source: yes

- name: Start subtensor service
  community.docker.docker_compose_v2:
    project_src: /opt/subtensor
    state: present
    services:
      - mainnet-lite
