---
- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure Docker service is enabled and started
  systemd:
    name: docker
    state: started
    enabled: yes
