---
# Handlers for IPFS service

- name: Restart IPFS service
  systemd:
    name: ipfs
    state: restarted
  become: yes

- name: Restart HAProxy service
  systemd:
    name: haproxy
    state: restarted
  become: yes 