---
- name: Download Kubo IPFS
  get_url:
    url: "{{ ipfs_download_url }}"
    dest: /tmp/kubo.tar.gz
    mode: '0755'

- name: Extract Kubo IPFS
  unarchive:
    src: /tmp/kubo.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install Kubo IPFS
  command: bash /tmp/kubo/install.sh
  args:
    creates: /usr/local/bin/ipfs

- name: Create IPFS user
  user:
    name: "{{ ipfs_user }}"
    system: yes
    shell: /bin/false
    create_home: yes
    home: "{{ ipfs_home }}"

- name: Create IPFS directory
  file:
    path: "{{ ipfs_data_dir }}"
    state: directory
    owner: "{{ ipfs_user }}"
    group: "{{ ipfs_group }}"
    mode: '0755'

- name: Initialize IPFS
  command: ipfs init --profile=server
  become: yes
  become_user: "{{ ipfs_user }}"
  args:
    creates: "{{ ipfs_data_dir }}/config"

- name: Configure IPFS API address
  command: ipfs config Addresses.API "{{ ipfs_api_address }}"
  become: yes
  become_user: "{{ ipfs_user }}"

- name: Configure IPFS Gateway address
  command: ipfs config Addresses.Gateway "{{ ipfs_gateway_address }}"
  become: yes
  become_user: "{{ ipfs_user }}"

- name: Create IPFS systemd service
  template:
    src: ipfs.service.j2
    dest: /etc/systemd/system/ipfs.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start IPFS service
  systemd:
    name: ipfs
    state: started
    enabled: yes
